# Generated by Django 4.2.20 on 2025-03-25 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('ghl_id', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('ghl_id', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.CharField(max_length=255)),
                ('property_address', models.CharField(max_length=500)),
                ('loan_purpose', models.CharField(db_index=True, max_length=20)),
                ('as_is_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rehab_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_to_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('after_repaired_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_type', models.CharField(db_index=True, max_length=50)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prepayment_penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origination_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_to_from_borrower', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lender_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_liquidity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('processing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_type', models.CharField(max_length=50)),
                ('annual_taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fico_score', models.IntegerField()),
                ('annual_insurance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fair_market_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_flood_insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('property_designation', models.CharField(max_length=100)),
                ('annual_hoa_dues', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_dscr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bankruptcy_last_3yrs', models.CharField(max_length=255)),
                ('foreclosures_last_3yrs', models.CharField(max_length=255)),
                ('felonies_crimes', models.CharField(max_length=255)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='term_data', to='term_sheet.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='TermSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdf_sheets/')),
                ('term_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='term_sheet', to='term_sheet.termdata')),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='term_sheet.pipeline'),
        ),
    ]
