# Generated by Django 4.2.20 on 2025-03-24 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('term_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipeline',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
