# Generated by Django 4.2.20 on 2025-03-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term_sheet', '0002_pipeline_date_added_pipeline_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termdata',
            name='contact',
        ),
    ]
