# Generated by Django 4.2.20 on 2025-03-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_sheet', '0003_alter_termdata_additional_liquidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termdata',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
