# Generated by Django 4.2.20 on 2025-05-05 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customfield'),
        ('term_sheet', '0005_alter_termdata_after_repaired_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customfield')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='term_sheet.opportunity')),
            ],
            options={
                'unique_together': {('opportunity', 'custom_field')},
            },
        ),
    ]
