# Generated by Django 4.2.20 on 2025-05-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_sheet', '0006_opportunitycustomfieldvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='LocationId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
