# Generated by Django 4.2.20 on 2025-05-07 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('term_sheet', '0009_opportunity_opp_value_opportunity_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('llc_name', models.CharField(max_length=255)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_type', models.CharField(max_length=100)),
                ('loan_term', models.CharField(max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_apr', models.DecimalField(decimal_places=3, max_digits=5)),
                ('occupancy', models.CharField(max_length=100)),
                ('applicant', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preapprovals', to='term_sheet.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='PreApprovalSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pre_approval_pdf_sheets/')),
                ('pre_approval', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_approval', to='term_sheet.preapproval')),
            ],
        ),
    ]
