# Generated by Django 4.2.20 on 2025-05-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_sheet', '0010_preapproval_preapprovalsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preapproval',
            name='loan_term',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='preapproval',
            name='loan_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='preapproval',
            name='rate_apr',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
