# Generated by Django 4.2.20 on 2025-05-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_sheet', '0012_alter_preapproval_rate_apr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preapproval',
            name='loan_amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='preapproval',
            name='purchase_price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='preapproval',
            name='rate_apr',
            field=models.CharField(max_length=255),
        ),
    ]
