# Generated by Django 4.2.20 on 2025-05-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_sheet', '0015_alter_opportunity_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='preapproval',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
