# Generated by Django 4.2.20 on 2025-05-05 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customfield'),
        ('contacts', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='contacts.contact')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customfield')),
            ],
            options={
                'unique_together': {('contact', 'custom_field')},
            },
        ),
    ]
