# Generated by Django 4.2.20 on 2025-03-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=500)),
                ('token_type', models.CharField(default='Brearer', max_length=100)),
                ('expires_at', models.DateField()),
                ('refresh_token', models.CharField(max_length=500)),
                ('scope', models.CharField(max_length=500)),
                ('userType', models.CharField(max_length=500)),
                ('companyId', models.CharField(max_length=500)),
                ('LocationId', models.CharField(max_length=500)),
                ('userId', models.CharField(max_length=500)),
            ],
        ),
    ]
